/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.ability.parametrizar.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import la.abality.parametrizar.model.T065BACIUDGENE;
import la.abality.parametrizar.service.T065BACIUDGENELocalServiceUtil;

/**
 * The extended model base implementation for the T065BACIUDGENE service. Represents a row in the &quot;service_T065BACIUDGENE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link T065BACIUDGENEImpl}.
 * </p>
 *
 * @author VillarTechnologies
 * @see T065BACIUDGENEImpl
 * @see la.abality.parametrizar.model.T065BACIUDGENE
 * @generated
 */
public abstract class T065BACIUDGENEBaseImpl extends T065BACIUDGENEModelImpl
	implements T065BACIUDGENE {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t065 b a c i u d g e n e model instance should use the {@link T065BACIUDGENE} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			T065BACIUDGENELocalServiceUtil.addT065BACIUDGENE(this);
		}
		else {
			T065BACIUDGENELocalServiceUtil.updateT065BACIUDGENE(this);
		}
	}
}