/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.ability.parametrizar.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import la.abality.parametrizar.model.T065BACIUDGENE;
import la.abality.parametrizar.model.T065BACIUDGENEModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the T065BACIUDGENE service. Represents a row in the &quot;service_T065BACIUDGENE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link la.abality.parametrizar.model.T065BACIUDGENEModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link T065BACIUDGENEImpl}.
 * </p>
 *
 * @author VillarTechnologies
 * @see T065BACIUDGENEImpl
 * @see la.abality.parametrizar.model.T065BACIUDGENE
 * @see la.abality.parametrizar.model.T065BACIUDGENEModel
 * @generated
 */
public class T065BACIUDGENEModelImpl extends BaseModelImpl<T065BACIUDGENE>
	implements T065BACIUDGENEModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t065 b a c i u d g e n e model instance should use the {@link la.abality.parametrizar.model.T065BACIUDGENE} interface instead.
	 */
	public static final String TABLE_NAME = "service_T065BACIUDGENE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "A065CODICIUD", Types.VARCHAR },
			{ "A065DESCCIUD", Types.VARCHAR },
			{ "A065CODIORG", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table service_T065BACIUDGENE (A065CODICIUD VARCHAR(75) not null primary key,A065DESCCIUD VARCHAR(75) null,A065CODIORG VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table service_T065BACIUDGENE";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.la.abality.parametrizar.model.T065BACIUDGENE"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.la.abality.parametrizar.model.T065BACIUDGENE"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.la.abality.parametrizar.model.T065BACIUDGENE"));

	public T065BACIUDGENEModelImpl() {
	}

	public String getPrimaryKey() {
		return _A065CODICIUD;
	}

	public void setPrimaryKey(String primaryKey) {
		setA065CODICIUD(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _A065CODICIUD;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return T065BACIUDGENE.class;
	}

	public String getModelClassName() {
		return T065BACIUDGENE.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("A065CODICIUD", getA065CODICIUD());
		attributes.put("A065DESCCIUD", getA065DESCCIUD());
		attributes.put("A065CODIORG", getA065CODIORG());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String A065CODICIUD = (String)attributes.get("A065CODICIUD");

		if (A065CODICIUD != null) {
			setA065CODICIUD(A065CODICIUD);
		}

		String A065DESCCIUD = (String)attributes.get("A065DESCCIUD");

		if (A065DESCCIUD != null) {
			setA065DESCCIUD(A065DESCCIUD);
		}

		String A065CODIORG = (String)attributes.get("A065CODIORG");

		if (A065CODIORG != null) {
			setA065CODIORG(A065CODIORG);
		}
	}

	public String getA065CODICIUD() {
		if (_A065CODICIUD == null) {
			return StringPool.BLANK;
		}
		else {
			return _A065CODICIUD;
		}
	}

	public void setA065CODICIUD(String A065CODICIUD) {
		_A065CODICIUD = A065CODICIUD;
	}

	public String getA065DESCCIUD() {
		if (_A065DESCCIUD == null) {
			return StringPool.BLANK;
		}
		else {
			return _A065DESCCIUD;
		}
	}

	public void setA065DESCCIUD(String A065DESCCIUD) {
		_A065DESCCIUD = A065DESCCIUD;
	}

	public String getA065CODIORG() {
		if (_A065CODIORG == null) {
			return StringPool.BLANK;
		}
		else {
			return _A065CODIORG;
		}
	}

	public void setA065CODIORG(String A065CODIORG) {
		_A065CODIORG = A065CODIORG;
	}

	@Override
	public T065BACIUDGENE toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (T065BACIUDGENE)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		T065BACIUDGENEImpl t065baciudgeneImpl = new T065BACIUDGENEImpl();

		t065baciudgeneImpl.setA065CODICIUD(getA065CODICIUD());
		t065baciudgeneImpl.setA065DESCCIUD(getA065DESCCIUD());
		t065baciudgeneImpl.setA065CODIORG(getA065CODIORG());

		t065baciudgeneImpl.resetOriginalValues();

		return t065baciudgeneImpl;
	}

	public int compareTo(T065BACIUDGENE t065baciudgene) {
		String primaryKey = t065baciudgene.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		T065BACIUDGENE t065baciudgene = null;

		try {
			t065baciudgene = (T065BACIUDGENE)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = t065baciudgene.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<T065BACIUDGENE> toCacheModel() {
		T065BACIUDGENECacheModel t065baciudgeneCacheModel = new T065BACIUDGENECacheModel();

		t065baciudgeneCacheModel.A065CODICIUD = getA065CODICIUD();

		String A065CODICIUD = t065baciudgeneCacheModel.A065CODICIUD;

		if ((A065CODICIUD != null) && (A065CODICIUD.length() == 0)) {
			t065baciudgeneCacheModel.A065CODICIUD = null;
		}

		t065baciudgeneCacheModel.A065DESCCIUD = getA065DESCCIUD();

		String A065DESCCIUD = t065baciudgeneCacheModel.A065DESCCIUD;

		if ((A065DESCCIUD != null) && (A065DESCCIUD.length() == 0)) {
			t065baciudgeneCacheModel.A065DESCCIUD = null;
		}

		t065baciudgeneCacheModel.A065CODIORG = getA065CODIORG();

		String A065CODIORG = t065baciudgeneCacheModel.A065CODIORG;

		if ((A065CODIORG != null) && (A065CODIORG.length() == 0)) {
			t065baciudgeneCacheModel.A065CODIORG = null;
		}

		return t065baciudgeneCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{A065CODICIUD=");
		sb.append(getA065CODICIUD());
		sb.append(", A065DESCCIUD=");
		sb.append(getA065DESCCIUD());
		sb.append(", A065CODIORG=");
		sb.append(getA065CODIORG());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("la.abality.parametrizar.model.T065BACIUDGENE");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>A065CODICIUD</column-name><column-value><![CDATA[");
		sb.append(getA065CODICIUD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>A065DESCCIUD</column-name><column-value><![CDATA[");
		sb.append(getA065DESCCIUD());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>A065CODIORG</column-name><column-value><![CDATA[");
		sb.append(getA065CODIORG());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = T065BACIUDGENE.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			T065BACIUDGENE.class
		};
	private String _A065CODICIUD;
	private String _A065DESCCIUD;
	private String _A065CODIORG;
	private T065BACIUDGENE _escapedModelProxy;
}