/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.abality.parametrizar.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the T065BACIUDGENE service. Represents a row in the &quot;service_T065BACIUDGENE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.abality.parametrizar.model.impl.T065BACIUDGENEModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.abality.parametrizar.model.impl.T065BACIUDGENEImpl}.
 * </p>
 *
 * @author VillarTechnologies
 * @see T065BACIUDGENE
 * @see la.abality.parametrizar.model.impl.T065BACIUDGENEImpl
 * @see la.abality.parametrizar.model.impl.T065BACIUDGENEModelImpl
 * @generated
 */
public interface T065BACIUDGENEModel extends BaseModel<T065BACIUDGENE> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t065 b a c i u d g e n e model instance should use the {@link T065BACIUDGENE} interface instead.
	 */

	/**
	 * Returns the primary key of this t065 b a c i u d g e n e.
	 *
	 * @return the primary key of this t065 b a c i u d g e n e
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this t065 b a c i u d g e n e.
	 *
	 * @param primaryKey the primary key of this t065 b a c i u d g e n e
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the a065 c o d i c i u d of this t065 b a c i u d g e n e.
	 *
	 * @return the a065 c o d i c i u d of this t065 b a c i u d g e n e
	 */
	@AutoEscape
	public String getA065CODICIUD();

	/**
	 * Sets the a065 c o d i c i u d of this t065 b a c i u d g e n e.
	 *
	 * @param A065CODICIUD the a065 c o d i c i u d of this t065 b a c i u d g e n e
	 */
	public void setA065CODICIUD(String A065CODICIUD);

	/**
	 * Returns the a065 d e s c c i u d of this t065 b a c i u d g e n e.
	 *
	 * @return the a065 d e s c c i u d of this t065 b a c i u d g e n e
	 */
	@AutoEscape
	public String getA065DESCCIUD();

	/**
	 * Sets the a065 d e s c c i u d of this t065 b a c i u d g e n e.
	 *
	 * @param A065DESCCIUD the a065 d e s c c i u d of this t065 b a c i u d g e n e
	 */
	public void setA065DESCCIUD(String A065DESCCIUD);

	/**
	 * Returns the a065 c o d i o r g of this t065 b a c i u d g e n e.
	 *
	 * @return the a065 c o d i o r g of this t065 b a c i u d g e n e
	 */
	@AutoEscape
	public String getA065CODIORG();

	/**
	 * Sets the a065 c o d i o r g of this t065 b a c i u d g e n e.
	 *
	 * @param A065CODIORG the a065 c o d i o r g of this t065 b a c i u d g e n e
	 */
	public void setA065CODIORG(String A065CODIORG);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(T065BACIUDGENE t065baciudgene);

	public int hashCode();

	public CacheModel<T065BACIUDGENE> toCacheModel();

	public T065BACIUDGENE toEscapedModel();

	public String toString();

	public String toXmlString();
}